import 'package:basic_restaurant_app/common/index.dart';
import 'package:basic_restaurant_app/core/index.dart';
import 'package:basic_restaurant_app/domain/category/index.dart';
import 'package:basic_restaurant_app/domain/food/index.dart';
import 'package:cached_network_image/cached_network_image.dart';
import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:get/get.dart';

part 'controllers/home_controller.dart';
part 'pages/home_view.dart';
part 'widgets/filtered_section.dart';
part 'widgets/food_card.dart';
part 'widgets/home_header.dart';
part 'widgets/home_view_body.dart';
part 'widgets/menu_tabs.dart';
part 'widgets/menu_tabs_delegate.dart';
part 'widgets/section_header.dart';
part 'widgets/view_order_button.dart';